apiVersion: apps/v1
kind: Deployment

metadata:
  name: secret-demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: secret-demo

  template:
    metadata:
      labels:
        app: secret-demo

    spec:
      containers:
      - name: nginx
        image: nginx

        env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DATABASE_USERNAME

        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DATABASE_PASSWORD
