apiVersion: batch/v1
kind: Job

metadata:
  name: failed-job

spec:
  backoffLimit: 3

  template:
    spec:
      containers:
      - name: fail
        image: busybox

        command:
        - sh
        - -c
        - exit 1

      restartPolicy: Never
