apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: configmap-demo

  template:
    metadata:
      labels:
        app: configmap-demo

    spec:
      containers:
      - name: demo-container
        image: nginx

        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV

        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATABASE_HOST

        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOG_LEVEL
