apiVersion: v1
kind: Pod

metadata:
  name: readiness-fail

spec:
  containers:
  - name: busybox
    image: busybox

    command:
    - sh
    - -c
    - |
      touch /tmp/ready
      sleep 30
      rm -f /tmp/ready
      while true; do sleep 5; done

    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready

      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 3
